### ISSUE TITLE
The rocketmq example is not startup in versions above springboot2

### ISSUE THREAD

**Issue by klaus-pd** [apache/rocketmq-externals#151]
RT

**Comment by techzealot** [comment]
## in application.properties, change spring.rocketmq.name-server to spring.rocketmq.nameServer,it will works.   
## The reason is that in spring-boot-starter-rocketmq, @ConditionalOnProperty(prefix = "spring.rocketmq", value = {"nameServer", "producer.group"})(org.apache.rocketmq.spring.starter.RocketMQAutoConfiguration) at line 83;   
## in springboot2 prefers name-server

**Comment by shibd** [comment]
为什么不和文档上的一致呢？
