### ISSUE TITLE
The problem of rocketmq-console permission

### ISSUE THREAD

**Issue by JingSpring** [apache/rocketmq-externals#707]
What's the difference between the administrator role and the ordinary user role of rocketmq console? When testing, I found that the permissions were the same.

**Comment by zhangjidi2016** [comment]
Currently, there are two types of users on the console, admin and common users. The admin user has the permission to access all interfaces, and the common user has the permission to view resources but cannot operate related resources. To do this, I'm going to implement a simple permission verification feature.

1. When the login user calls all interfaces, the permission of each interface is verified by AOP, by checking whether the role to which the user belongs has the access permission of the interface. All interface urls that a common user role has access permissions are saved in a file. The file is hot updated to facilitate adding or deleting permissions.

2. In the interface, in order to distinguish admin from ordinary users more easily, the buttons for creating, updating and deleting operations are not displayed for ordinary users.

Please help to evaluate whether this scheme is feasible? @francisoliverlee @vongosling

**Comment by vongosling** [comment]
@StyleTang Thoughts?

**Comment by StyleTang** [comment]
LGTM
It would be great if console have the features which have been mentioned. 

1. Use AOP to do the resource permission control is a good way, and hot update is very convenient for admin to use (maybe we can also provide a page for admin to maintain the roles and users)
2. Using permissions to control the display can provide a good user experience.

We may introduce the RBAC permission control, at the beginning we can have admin and common user. Later, we can have more detailed control, such as which users can manage which topics, different user can have different permissions.

**Comment by vongosling** [comment]
Cool, we could push forward in this direction.
