### ISSUE TITLE
[rocketmq-connect-runtime] WorkerDirectTask put position error

### ISSUE THREAD

**Issue by Slideee** [apache/rocketmq-externals#866]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
![image](https://user-images.githubusercontent.com/48793283/154399921-f21a7813-a4f5-4468-8835-2bb7df85bdf7.png)

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Stale / Needs Info**

This issue was filed in 2022 with only an image attachment and no description. The rocketmq-connect-runtime code has been moved to [apache/rocketmq-connect](https://github.com/apache/rocketmq-connect).

If this issue is still relevant, please provide:
- [ ] Steps to reproduce
- [ ] Expected vs actual behavior
- [ ] Version information
- [ ] Relevant logs or stack traces

---
*Automated evaluation by RockteMQ-AI*
